name: Aplicar cambios de Vercel

on:
  push:
    branches:
      - main

jobs:
  actualizar-código:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2

      - name: Aplicar cambios sugeridos por Vercel
        run: |
          # Aquí puedes ejecutar scripts para aplicar cambios
          # Por ejemplo, actualizar dependencias o modificar archivos
          npm install

      - name: Commit y push cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Aplicar cambios sugeridos por Vercel" || echo "No hay cambios para commitear"
          git push
